name: learn-github-actions
on: [workflow_dispatch]
jobs: 
  hello-actions: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "This is our first github workflow!"
