name: "Deployment of python app"
on: 
  pull_request:
    paths:
      - 'lint_test.py'
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This has been triggered ${{ github.event_name }} event"
      - run: echo "This runs on ${{ runner.os }} event"
      - name: Checkout Repository Code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Lint with pylint
        run: |
          python lint_test.py
      - name: Build container
        run: |
          echo "Building container image...."
          sleep 30

  
