name: "Deployment of python app"
on: [push]
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This has been triggered ${{ github.event_name }} event"
      - run: echo "This runs on ${{ runner.os }} event"
      - name: Checkout Repository Code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: python –m pip install –upgrade pip
      - run: pip install pylint
      - run: python lint_test.py
  
