name: "Deployment of python app"
on: [pull_request]
jobs: 
  new_pull_request_notification:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This runs on ${{ runner.os }} event"
      - name: Post to a Slack channel Notification for new PR
        id: slack
        uses: slackapi/slack-github-action@v1.15.0
        with:
          channel-id: '#upskill-devops-course'  # Slack channel id or name to post message. https://api.slack.com/methods/chat.postMessage#channels
          slack-message: 'New Pull Request Created in repository mayamitova/telerik-github-actions-2021'
        env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
